version: "3.7"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  develop:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev -H 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
